version: '3.1'
services:
  mycassandra:
    image: cassandra
    container_name: TweetAppcassandra
    ports:
      - "9042:9042"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: tweet-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: tweet-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'userauth:1:1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    depends_on:
      - "zookeeper"